# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class InstagramSourceConfig(config.Config):
    access_token: str
    login_type: Literal["instagram", "facebook"] = config.value(default="instagram")
    instagram_account_id: str | None = None
    app_secret: str | None = None
    start_date: str | None = None
